"""add evolution run review fields and audit log table

Revision ID: 4af3c7ed9419
Revises: e5f6a7b8c9d0
Create Date: 2026-02-16 14:06:14.960864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4af3c7ed9419'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('code_content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='algorithm_status_enum'), nullable=False),
    sa.Column('source_law_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('function_name', 'version', name='uq_algorithm_func_version')
    )
    op.create_index('ix_algorithm_func_version', 'algorithm_registry', ['function_name', 'version'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('profile_definitions',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('schema_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('income_type', sa.Enum('SALARY', 'BONUS', 'OTHER', name='income_type_enum'), nullable=False),
    sa.Column('gross_amount', sa.Integer(), nullable=False),
    sa.Column('social_insurance', sa.Integer(), nullable=False),
    sa.Column('withholding_tax', sa.Integer(), nullable=False),
    sa.Column('resident_tax', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_entries_user_date', 'income_entries', ['user_id', 'payment_date'], unique=False)
    op.create_table('tax_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('has_spouse', sa.Boolean(), nullable=False),
    sa.Column('dependents_count', sa.Integer(), nullable=False),
    sa.Column('social_insurance_premium', sa.Integer(), nullable=False),
    sa.Column('life_insurance_premium', sa.Integer(), nullable=False),
    sa.Column('ideco_monthly_contribution', sa.Integer(), nullable=False),
    sa.Column('additional_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', name='uq_tax_profile_user_year')
    )
    op.create_index('ix_tax_profiles_user_year', 'tax_profiles', ['user_id', 'year'], unique=False)
    op.add_column('evolution_runs', sa.Column('review_decision', sa.String(length=30), nullable=True))
    op.add_column('evolution_runs', sa.Column('rationale', sa.Text(), nullable=True))
    op.add_column('evolution_runs', sa.Column('modified_code', sa.Text(), nullable=True))
    op.add_column('evolution_runs', sa.Column('regeneration_hints', sa.Text(), nullable=True))
    op.add_column('evolution_runs', sa.Column('regeneration_count', sa.Integer(), nullable=False))
    op.add_column('evolution_runs', sa.Column('max_regenerations', sa.Integer(), nullable=False))
    op.add_column('evolution_runs', sa.Column('activated_algorithm_id', sa.Integer(), nullable=True))
    op.add_column('evolution_runs', sa.Column('schema_proposal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'evolution_runs', 'schema_change_proposals', ['schema_proposal_id'], ['id'])
    op.create_foreign_key(None, 'evolution_runs', 'algorithm_registry', ['activated_algorithm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evolution_runs', type_='foreignkey')
    op.drop_constraint(None, 'evolution_runs', type_='foreignkey')
    op.drop_column('evolution_runs', 'schema_proposal_id')
    op.drop_column('evolution_runs', 'activated_algorithm_id')
    op.drop_column('evolution_runs', 'max_regenerations')
    op.drop_column('evolution_runs', 'regeneration_count')
    op.drop_column('evolution_runs', 'regeneration_hints')
    op.drop_column('evolution_runs', 'modified_code')
    op.drop_column('evolution_runs', 'rationale')
    op.drop_column('evolution_runs', 'review_decision')
    op.drop_index('ix_tax_profiles_user_year', table_name='tax_profiles')
    op.drop_table('tax_profiles')
    op.drop_index('ix_income_entries_user_date', table_name='income_entries')
    op.drop_table('income_entries')
    op.drop_table('users')
    op.drop_table('profile_definitions')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_algorithm_func_version', table_name='algorithm_registry')
    op.drop_table('algorithm_registry')
    # ### end Alembic commands ###
