"""add notification tables with correct schema

Revision ID: 4ec72eb97686
Revises: b76c461c7095
Create Date: 2026-02-16 15:07:07.995234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ec72eb97686'
down_revision: Union[str, Sequence[str], None] = 'b76c461c7095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('smtp_host', sa.String(length=200), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_user', sa.String(length=200), nullable=False),
    sa.Column('encrypted_smtp_password', sa.Text(), nullable=False),
    sa.Column('sender_email', sa.String(length=200), nullable=False),
    sa.Column('recipient_emails', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('recipient_emails', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('evolution_run_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evolution_run_id'], ['evolution_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_logs_event_sent', 'notification_logs', ['event', 'sent_at'], unique=False)
    op.create_index('ix_notification_logs_evolution_run_id', 'notification_logs', ['evolution_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_logs_evolution_run_id', table_name='notification_logs')
    op.drop_index('ix_notification_logs_event_sent', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_table('notification_configs')
    # ### end Alembic commands ###
