"""add_source_type_to_nta_target_pages

Revision ID: 8afe37637f8a
Revises: 4ec72eb97686
Create Date: 2026-02-16 16:08:13.446316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afe37637f8a'
down_revision: Union[str, Sequence[str], None] = '4ec72eb97686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nta_target_pages', sa.Column('source_type', sa.String(length=30), server_default='NTA_TAX_ANSWER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nta_target_pages', 'source_type')
    # ### end Alembic commands ###
