"""initial schema

Revision ID: ac1e2508ad42
Revises: 
Create Date: 2026-02-13 07:07:29.458300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac1e2508ad42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('function_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('code_content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='algorithm_status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_definitions',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('schema_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('income_type', sa.Enum('SALARY', 'BONUS', 'OTHER', name='income_type_enum'), nullable=False),
    sa.Column('gross_amount', sa.Integer(), nullable=False),
    sa.Column('social_insurance', sa.Integer(), nullable=False),
    sa.Column('withholding_tax', sa.Integer(), nullable=False),
    sa.Column('resident_tax', sa.Integer(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('has_spouse', sa.Boolean(), nullable=False),
    sa.Column('dependents_count', sa.Integer(), nullable=False),
    sa.Column('social_insurance_premium', sa.Integer(), nullable=False),
    sa.Column('life_insurance_premium', sa.Integer(), nullable=False),
    sa.Column('ideco_monthly_contribution', sa.Integer(), nullable=False),
    sa.Column('additional_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tax_profiles_user_year', 'tax_profiles', ['user_id', 'year'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tax_profiles_user_year', table_name='tax_profiles')
    op.drop_table('tax_profiles')
    op.drop_table('income_entries')
    op.drop_table('users')
    op.drop_table('profile_definitions')
    op.drop_table('algorithm_registry')
    # ### end Alembic commands ###
