"""fix circular dependency with use_alter flag

Revision ID: b76c461c7095
Revises: 4af3c7ed9419
Create Date: 2026-02-16 14:10:41.721855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76c461c7095'
down_revision: Union[str, Sequence[str], None] = '4af3c7ed9419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
