"""Add locale_preference to users

Revision ID: df27a3db94c6
Revises: 8afe37637f8a
Create Date: 2026-02-17 03:57:42.045770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df27a3db94c6'
down_revision: Union[str, Sequence[str], None] = '8afe37637f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale_preference', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale_preference')
    # ### end Alembic commands ###
